# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1385500762);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1385500882);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1385500522);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1385500642);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.lastDir", "/h/u5/g2/00/g2chenri/apache/htdocs");
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20131115110311");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20131115110311");
user_pref("browser.startup.homepage_override.mstone", "25.0.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1385500465252");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1385500467243");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1385586867243");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1385249867800");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1385254196587");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-dismissed");
user_pref("datareporting.policy.firstRunTime", "1384897803911");
user_pref("datareporting.sessions.current.activeTicks", 175);
user_pref("datareporting.sessions.current.firstPaint", 5761);
user_pref("datareporting.sessions.current.main", 4190);
user_pref("datareporting.sessions.current.sessionRestored", 5922);
user_pref("datareporting.sessions.current.startTime", "1385500397006");
user_pref("datareporting.sessions.current.totalTime", 1812);
user_pref("datareporting.sessions.currentIndex", 49);
user_pref("datareporting.sessions.prunedIndex", 48);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_INSPECTOR_OPENED_PER_USER_FLAG\":\"25.0.1\",\"DEVTOOLS_RULEVIEW_OPENED_PER_USER_FLAG\":\"25.0.1\",\"DEVTOOLS_JSDEBUGGER_OPENED_PER_USER_FLAG\":\"25.0.1\",\"DEVTOOLS_WEBCONSOLE_OPENED_PER_USER_FLAG\":\"25.0.1\",\"DEVTOOLS_JSPROFILER_OPENED_PER_USER_FLAG\":\"25.0.1\"}");
user_pref("devtools.toolbox.footer.height", 132);
user_pref("devtools.toolbox.host", "window");
user_pref("devtools.toolbox.selectedTool", "jsdebugger");
user_pref("devtools.toolsidebar-width.inspector", 0);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:25.0.1");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1384971003000,\"rdfTime\":1384515779000}}}]");
user_pref("extensions.lastAppVersion", "25.0.1");
user_pref("extensions.lastPlatformVersion", "25.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20131115110311");
user_pref("gecko.mstone", "25.0.1");
user_pref("idle.lastDailyNotification", 1385502276);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1385500466);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1385065460);
user_pref("toolkit.startup.last_success", 1385500401);
user_pref("toolkit.telemetry.previousBuildID", "20131115110311");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1387489808);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
