# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20131028113308");
user_pref("browser.slowStartup.averageTime", 811);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20131028113308");
user_pref("browser.startup.homepage_override.mstone", "25.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1384984203912");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1384897803911");
user_pref("datareporting.sessions.current.activeTicks", 4);
user_pref("datareporting.sessions.current.firstPaint", 727);
user_pref("datareporting.sessions.current.main", 31);
user_pref("datareporting.sessions.current.sessionRestored", 821);
user_pref("datareporting.sessions.current.startTime", "1384898254300");
user_pref("datareporting.sessions.current.totalTime", 20);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.0", "{\"s\":1384897758613,\"a\":4,\"t\":63,\"c\":true,\"m\":44690,\"fp\":47227,\"sr\":47919}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1384897822514,\"a\":18,\"t\":94,\"c\":true,\"m\":4020,\"fp\":4850,\"sr\":4961}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1384897940385,\"a\":6,\"t\":64,\"c\":true,\"m\":21,\"fp\":731,\"sr\":839}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1384898126197,\"a\":2,\"t\":7,\"c\":true,\"m\":31,\"fp\":790,\"sr\":897}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1384898138006,\"a\":1,\"t\":1,\"c\":true,\"m\":32,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1384898145212,\"a\":1,\"t\":2,\"c\":true,\"m\":30,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1384898150709,\"a\":16,\"t\":89,\"c\":true,\"m\":20,\"fp\":796,\"sr\":893}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:25.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1383136529000,\"rdfTime\":1382962391000}}}]");
user_pref("extensions.lastAppVersion", "25.0");
user_pref("extensions.lastPlatformVersion", "25.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20131028113308");
user_pref("gecko.mstone", "25.0");
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1384898254);
user_pref("toolkit.telemetry.previousBuildID", "20131028113308");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1387489808);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
